// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

TableData loadCsvToFlutter({required String name, required String csv}) =>
    RustLib.instance.api.crateBridgeLoadCsvToFlutter(name: name, csv: csv);

class TableData {
  final String name;
  final List<String> columns;
  final List<List<String>> rows;

  const TableData({
    required this.name,
    required this.columns,
    required this.rows,
  });

  @override
  int get hashCode => name.hashCode ^ columns.hashCode ^ rows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TableData &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          columns == other.columns &&
          rows == other.rows;
}
